---
#- hosts: debian
#  become: yes

#  tasks:
#  - name: "Instala o pacote curl no Debian"
#    apt:
#      update_cache: yes
#      name: "curl"
#      state: present

- hosts: all
  become: yes
  gather_facts: yes

  vars:
    default_dir: /opt/custom
    teste: "{{ default_dir }}/scripts"
    dict_dir: {
      scripts: "{{ default_dir }}/bin",
      backup: "{{ default_dir }}/backup",
      log: "{{ default_dir }}/log",
      temp: "{{ default_dir }}/temp",
    }

  tasks:
  - name: "Instala o pacote curl para Debian"
    apt:
      update_cache: yes
      name: "curl"
      state: present
    when: (ansible_facts['distribution'] == "Debian")

  - name: "DEFINE HOSTNAME SERVIDORES"
    hostname:
      name: "{{ hostname }}"

  - name: "CRIA DIRETORIO PADRAO NOS SERVIDORES"
    file:
      path: "{{ item }}"
      owner: antiddosmyrai
      group: antiddosmyrai
      state: directory
    with_items:
    - "{{ dict_dir.scripts}}"
    - "{{ dict_dir.backup}}"
    - "{{ dict_dir.log}}"
    - "{{ dict_dir.temp}}"
    #- "/opt/custom/scripts"
    #- "/opt/custom/backup"
    #- "/opt/custom/log"
    #- "/opt/custom/temp"
    #- "{{ default_dir }}/scripts"
    #- "{{ default_dir }}/backup"
    #- "{{ default_dir }}/log"
    #- "{{ default_dir }}/temp"


  - name: "CRIA ARQUIVO SIMPLES"
    file:
      path: "{{ default_dir }}/teste.py"
      state: touch
      owner: antiddosmyrai
      group: antiddosmyrai
      mode: 0755
      modification_time: preserve
      access_time: preserve

  - name: "exemplo de debug"
    debug:
      msg: "{{ dict_dir.scripts }}"

  - name: "EXEMPLO DE REGISTER"
    shell: "date -u"
    register: linux_date #variavel que armazena o comando date -u

  - name: "EXIBINDO REGISTER"
    debug:
      msg: "{{ linux_date.start }}"